steps:
- name: 'python:3.9'
  entrypoint: 'pip'
  args:
  - install
  - '-r'
  - 'requirements.txt'
  - '--target=./.cloudfunctions'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - hello_world2
  - --source=.
  - --trigger-http
  - --runtime=python39
  - --allow-unauthenticated
  - --set-env-vars=PYTHONPATH=./.cloudfunctions
